// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using OrderManagement.Backend;

namespace OrderManagement.Backend.Migrations
{
    [DbContext(typeof(OrderManagementDbContext))]
    [Migration("20210808105855_init")]
    partial class init
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.1");

            modelBuilder.Entity("OrderManagement.Backend.DataModels.Address", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PostCode")
                        .HasColumnType("int");

                    b.Property<string>("Street")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Addresses");

                    b.HasData(
                        new
                        {
                            Id = "1",
                            City = "Gossau",
                            Country = "Switzerland",
                            PostCode = 9200,
                            Street = "Gossauerstrasse 15"
                        },
                        new
                        {
                            Id = "2",
                            City = "Appenzell",
                            Country = "Switzerland",
                            PostCode = 9050,
                            Street = "Ronis 2"
                        },
                        new
                        {
                            Id = "3",
                            City = "Appenzell",
                            Country = "Switzerland",
                            PostCode = 9050,
                            Street = "Lehnmattstrasse 21"
                        },
                        new
                        {
                            Id = "4",
                            City = "Wil",
                            Country = "Switzerland",
                            PostCode = 9500,
                            Street = "Rebhofweg 10"
                        },
                        new
                        {
                            Id = "5",
                            City = "Burgdorf",
                            Country = "Switzerland",
                            PostCode = 3400,
                            Street = "Polieregasse 2"
                        },
                        new
                        {
                            Id = "6",
                            City = "Adelboden",
                            Country = "Switzerland",
                            PostCode = 3715,
                            Street = "Zelgstrasse 2"
                        },
                        new
                        {
                            Id = "7",
                            City = "Biasca",
                            Country = "Switzerland",
                            PostCode = 6710,
                            Street = "Via Lucomagno 115"
                        },
                        new
                        {
                            Id = "8",
                            City = "Muenstertal",
                            Country = "Switzerland",
                            PostCode = 7536,
                            Street = "Chasatschas 111"
                        },
                        new
                        {
                            Id = "9",
                            City = "Walenstadt",
                            Country = "Switzerland",
                            PostCode = 8880,
                            Street = "Walenseestrasse 34"
                        },
                        new
                        {
                            Id = "10",
                            City = "Kreuzlingen",
                            Country = "Switzerland",
                            PostCode = 8280,
                            Street = "Sonnenstrasse 35"
                        },
                        new
                        {
                            Id = "11",
                            City = "Muellheim",
                            Country = "Switzerland",
                            PostCode = 8555,
                            Street = "Bahnhofstrasse 16"
                        },
                        new
                        {
                            Id = "12",
                            City = "Frauenfeld",
                            Country = "Switzerland",
                            PostCode = 8500,
                            Street = "Kurzenerchingerstrasse 5"
                        },
                        new
                        {
                            Id = "13",
                            City = "Winterthur",
                            Country = "Switzerland",
                            PostCode = 8400,
                            Street = "Wartstrasse 16"
                        },
                        new
                        {
                            Id = "14",
                            City = "Nuerensdorf",
                            Country = "Switzerland",
                            PostCode = 8309,
                            Street = "Kanzleistrasse 4"
                        },
                        new
                        {
                            Id = "15",
                            City = "Kloten",
                            Country = "Switzerland",
                            PostCode = 8302,
                            Street = "Flughafenstrasse 25"
                        },
                        new
                        {
                            Id = "16",
                            City = "Dietikon",
                            Country = "Switzerland",
                            PostCode = 8953,
                            Street = "Oetwilerstrasse 13"
                        },
                        new
                        {
                            Id = "17",
                            City = "Gerlafingen",
                            Country = "Switzerland",
                            PostCode = 4563,
                            Street = "Muehlegasse 32"
                        },
                        new
                        {
                            Id = "18",
                            City = "Erlach",
                            Country = "Switzerland",
                            PostCode = 3235,
                            Street = "Altstadt 27"
                        },
                        new
                        {
                            Id = "19",
                            City = "Wuerzburg",
                            Country = "Germany",
                            PostCode = 97074,
                            Street = "Grasweg 2"
                        },
                        new
                        {
                            Id = "20",
                            City = "Bielefeld",
                            Country = "Germany",
                            PostCode = 33602,
                            Street = "August-Bebel-Strasse 108"
                        },
                        new
                        {
                            Id = "21",
                            City = "Bucharest",
                            Country = "Romania",
                            PostCode = 30167,
                            Street = "Strada Vasile Lascar 15"
                        });
                });

            modelBuilder.Entity("OrderManagement.Backend.DataModels.Customer", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("AddressId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Firstname")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Mail")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Webpage")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("AddressId");

                    b.ToTable("Customers");

                    b.HasData(
                        new
                        {
                            Id = "1",
                            AddressId = "1",
                            Firstname = "Alfred",
                            Name = "Koller"
                        },
                        new
                        {
                            Id = "2",
                            AddressId = "2",
                            Firstname = "Karl",
                            Name = "Meier"
                        },
                        new
                        {
                            Id = "3",
                            AddressId = "3",
                            Firstname = "Marco",
                            Name = "Ebneter"
                        },
                        new
                        {
                            Id = "4",
                            AddressId = "4",
                            Firstname = "Mike",
                            Name = "Faessler"
                        },
                        new
                        {
                            Id = "5",
                            AddressId = "5",
                            Firstname = "Remo",
                            Name = "Kessler"
                        },
                        new
                        {
                            Id = "6",
                            AddressId = "6",
                            Firstname = "Tim",
                            Name = "Manser"
                        },
                        new
                        {
                            Id = "7",
                            AddressId = "7",
                            Firstname = "Martin",
                            Name = "Streule"
                        },
                        new
                        {
                            Id = "8",
                            AddressId = "8",
                            Firstname = "Michael",
                            Name = "Messmer"
                        },
                        new
                        {
                            Id = "9",
                            AddressId = "9",
                            Firstname = "Berta",
                            Name = "Keiser"
                        },
                        new
                        {
                            Id = "10",
                            AddressId = "10",
                            Firstname = "Tobias",
                            Name = "Wirth"
                        },
                        new
                        {
                            Id = "11",
                            AddressId = "11",
                            Firstname = "Roland",
                            Name = "Zumstein"
                        },
                        new
                        {
                            Id = "12",
                            AddressId = "12",
                            Firstname = "Konrad",
                            Name = "Mazenauer"
                        },
                        new
                        {
                            Id = "13",
                            AddressId = "13",
                            Firstname = "Patrick",
                            Name = "Stadler"
                        },
                        new
                        {
                            Id = "14",
                            AddressId = "14",
                            Firstname = "Natascha",
                            Name = "Luechinger"
                        },
                        new
                        {
                            Id = "15",
                            AddressId = "15",
                            Firstname = "Stefanie",
                            Name = "Staub"
                        },
                        new
                        {
                            Id = "16",
                            AddressId = "16",
                            Firstname = "Emanuel",
                            Name = "Steingruber"
                        },
                        new
                        {
                            Id = "17",
                            AddressId = "17",
                            Firstname = "Nicole",
                            Name = "Fritsche"
                        },
                        new
                        {
                            Id = "18",
                            AddressId = "18",
                            Firstname = "Karin",
                            Name = "Geher"
                        },
                        new
                        {
                            Id = "19",
                            AddressId = "19",
                            Firstname = "Ruedi",
                            Name = "Wuerth"
                        },
                        new
                        {
                            Id = "20",
                            AddressId = "20",
                            Firstname = "Tamara",
                            Name = "Ebneter"
                        },
                        new
                        {
                            Id = "21",
                            AddressId = "21",
                            Firstname = "Antonia",
                            Name = "Faessler"
                        },
                        new
                        {
                            Id = "22",
                            AddressId = "8",
                            Firstname = "Alejandro",
                            Name = "Faessler"
                        },
                        new
                        {
                            Id = "23",
                            AddressId = "10",
                            Firstname = "Pascal",
                            Name = "Koller"
                        });
                });

            modelBuilder.Entity("OrderManagement.Backend.DataModels.Order", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("CustomerId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.ToTable("Orders");

                    b.HasData(
                        new
                        {
                            Id = "1",
                            CustomerId = "1",
                            Date = new DateTime(2020, 12, 10, 9, 10, 55, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = "2",
                            CustomerId = "2",
                            Date = new DateTime(2020, 11, 5, 9, 10, 55, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = "3",
                            CustomerId = "3",
                            Date = new DateTime(2020, 9, 12, 9, 10, 55, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = "4",
                            CustomerId = "4",
                            Date = new DateTime(2020, 2, 10, 9, 10, 55, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = "5",
                            CustomerId = "5",
                            Date = new DateTime(2020, 5, 10, 9, 10, 55, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = "6",
                            CustomerId = "6",
                            Date = new DateTime(2020, 6, 10, 9, 10, 55, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = "7",
                            CustomerId = "7",
                            Date = new DateTime(2020, 3, 15, 9, 10, 55, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = "8",
                            CustomerId = "8",
                            Date = new DateTime(2020, 2, 20, 9, 10, 55, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = "9",
                            CustomerId = "9",
                            Date = new DateTime(2020, 8, 25, 9, 10, 55, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = "10",
                            CustomerId = "10",
                            Date = new DateTime(2020, 11, 30, 9, 10, 55, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = "11",
                            CustomerId = "11",
                            Date = new DateTime(2019, 5, 13, 9, 10, 55, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = "12",
                            CustomerId = "12",
                            Date = new DateTime(2019, 5, 14, 9, 10, 55, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = "13",
                            CustomerId = "13",
                            Date = new DateTime(2019, 10, 5, 9, 10, 55, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = "14",
                            CustomerId = "14",
                            Date = new DateTime(2019, 12, 30, 9, 10, 55, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = "15",
                            CustomerId = "15",
                            Date = new DateTime(2019, 2, 23, 9, 10, 55, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = "16",
                            CustomerId = "16",
                            Date = new DateTime(2019, 1, 12, 9, 10, 55, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = "17",
                            CustomerId = "17",
                            Date = new DateTime(2019, 6, 28, 9, 10, 55, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = "18",
                            CustomerId = "18",
                            Date = new DateTime(2019, 8, 17, 9, 10, 55, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = "19",
                            CustomerId = "19",
                            Date = new DateTime(2018, 12, 18, 9, 10, 55, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = "20",
                            CustomerId = "20",
                            Date = new DateTime(2018, 11, 9, 9, 10, 55, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = "21",
                            CustomerId = "21",
                            Date = new DateTime(2018, 8, 3, 9, 10, 55, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = "22",
                            CustomerId = "22",
                            Date = new DateTime(2018, 2, 16, 9, 10, 55, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = "23",
                            CustomerId = "1",
                            Date = new DateTime(2018, 1, 11, 9, 10, 55, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = "24",
                            CustomerId = "2",
                            Date = new DateTime(2018, 5, 13, 9, 10, 55, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = "25",
                            CustomerId = "3",
                            Date = new DateTime(2018, 6, 12, 9, 10, 55, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = "26",
                            CustomerId = "4",
                            Date = new DateTime(2018, 4, 27, 9, 10, 55, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = "27",
                            CustomerId = "5",
                            Date = new DateTime(2017, 12, 26, 9, 10, 55, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = "28",
                            CustomerId = "6",
                            Date = new DateTime(2021, 12, 29, 9, 10, 55, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = "29",
                            CustomerId = "7",
                            Date = new DateTime(2017, 12, 26, 9, 10, 55, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("OrderManagement.Backend.DataModels.OrderPosition", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("Count")
                        .HasColumnType("int");

                    b.Property<string>("OrderId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("Position")
                        .HasColumnType("int");

                    b.Property<string>("ProductId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("OrderId");

                    b.HasIndex("ProductId");

                    b.ToTable("OrderPositions");

                    b.HasData(
                        new
                        {
                            Id = "1",
                            Count = 5,
                            OrderId = "1",
                            Position = 1,
                            ProductId = "1"
                        },
                        new
                        {
                            Id = "2",
                            Count = 3,
                            OrderId = "1",
                            Position = 2,
                            ProductId = "3"
                        },
                        new
                        {
                            Id = "3",
                            Count = 2,
                            OrderId = "2",
                            Position = 1,
                            ProductId = "1"
                        },
                        new
                        {
                            Id = "4",
                            Count = 1,
                            OrderId = "3",
                            Position = 1,
                            ProductId = "1"
                        },
                        new
                        {
                            Id = "5",
                            Count = 8,
                            OrderId = "3",
                            Position = 2,
                            ProductId = "1"
                        },
                        new
                        {
                            Id = "6",
                            Count = 12,
                            OrderId = "3",
                            Position = 3,
                            ProductId = "1"
                        },
                        new
                        {
                            Id = "7",
                            Count = 15,
                            OrderId = "3",
                            Position = 4,
                            ProductId = "1"
                        },
                        new
                        {
                            Id = "8",
                            Count = 9,
                            OrderId = "4",
                            Position = 1,
                            ProductId = "1"
                        },
                        new
                        {
                            Id = "9",
                            Count = 8,
                            OrderId = "4",
                            Position = 2,
                            ProductId = "1"
                        },
                        new
                        {
                            Id = "10",
                            Count = 4,
                            OrderId = "5",
                            Position = 1,
                            ProductId = "1"
                        },
                        new
                        {
                            Id = "11",
                            Count = 3,
                            OrderId = "6",
                            Position = 1,
                            ProductId = "1"
                        },
                        new
                        {
                            Id = "12",
                            Count = 5,
                            OrderId = "7",
                            Position = 1,
                            ProductId = "1"
                        },
                        new
                        {
                            Id = "13",
                            Count = 7,
                            OrderId = "7",
                            Position = 2,
                            ProductId = "1"
                        },
                        new
                        {
                            Id = "14",
                            Count = 26,
                            OrderId = "8",
                            Position = 1,
                            ProductId = "1"
                        },
                        new
                        {
                            Id = "15",
                            Count = 361,
                            OrderId = "9",
                            Position = 1,
                            ProductId = "1"
                        },
                        new
                        {
                            Id = "16",
                            Count = 20,
                            OrderId = "10",
                            Position = 1,
                            ProductId = "1"
                        },
                        new
                        {
                            Id = "17",
                            Count = 515,
                            OrderId = "11",
                            Position = 1,
                            ProductId = "1"
                        },
                        new
                        {
                            Id = "18",
                            Count = 2,
                            OrderId = "12",
                            Position = 1,
                            ProductId = "1"
                        },
                        new
                        {
                            Id = "19",
                            Count = 1,
                            OrderId = "13",
                            Position = 1,
                            ProductId = "1"
                        },
                        new
                        {
                            Id = "20",
                            Count = 8,
                            OrderId = "13",
                            Position = 2,
                            ProductId = "1"
                        },
                        new
                        {
                            Id = "21",
                            Count = 30,
                            OrderId = "13",
                            Position = 3,
                            ProductId = "1"
                        },
                        new
                        {
                            Id = "22",
                            Count = 40,
                            OrderId = "13",
                            Position = 4,
                            ProductId = "1"
                        },
                        new
                        {
                            Id = "23",
                            Count = 2,
                            OrderId = "14",
                            Position = 1,
                            ProductId = "1"
                        },
                        new
                        {
                            Id = "24",
                            Count = 7,
                            OrderId = "15",
                            Position = 1,
                            ProductId = "1"
                        },
                        new
                        {
                            Id = "25",
                            Count = 8,
                            OrderId = "16",
                            Position = 1,
                            ProductId = "1"
                        },
                        new
                        {
                            Id = "26",
                            Count = 5,
                            OrderId = "17",
                            Position = 1,
                            ProductId = "1"
                        },
                        new
                        {
                            Id = "27",
                            Count = 9,
                            OrderId = "18",
                            Position = 1,
                            ProductId = "1"
                        },
                        new
                        {
                            Id = "28",
                            Count = 3,
                            OrderId = "18",
                            Position = 2,
                            ProductId = "1"
                        },
                        new
                        {
                            Id = "29",
                            Count = 10,
                            OrderId = "19",
                            Position = 1,
                            ProductId = "1"
                        },
                        new
                        {
                            Id = "30",
                            Count = 20,
                            OrderId = "20",
                            Position = 1,
                            ProductId = "1"
                        },
                        new
                        {
                            Id = "31",
                            Count = 15,
                            OrderId = "21",
                            Position = 1,
                            ProductId = "1"
                        },
                        new
                        {
                            Id = "32",
                            Count = 88,
                            OrderId = "22",
                            Position = 1,
                            ProductId = "1"
                        },
                        new
                        {
                            Id = "33",
                            Count = 20,
                            OrderId = "23",
                            Position = 1,
                            ProductId = "1"
                        },
                        new
                        {
                            Id = "34",
                            Count = 30,
                            OrderId = "24",
                            Position = 1,
                            ProductId = "1"
                        },
                        new
                        {
                            Id = "35",
                            Count = 80,
                            OrderId = "25",
                            Position = 1,
                            ProductId = "1"
                        },
                        new
                        {
                            Id = "36",
                            Count = 90,
                            OrderId = "25",
                            Position = 2,
                            ProductId = "1"
                        },
                        new
                        {
                            Id = "37",
                            Count = 100,
                            OrderId = "25",
                            Position = 3,
                            ProductId = "1"
                        },
                        new
                        {
                            Id = "38",
                            Count = 42,
                            OrderId = "25",
                            Position = 4,
                            ProductId = "1"
                        },
                        new
                        {
                            Id = "39",
                            Count = 15,
                            OrderId = "25",
                            Position = 5,
                            ProductId = "1"
                        },
                        new
                        {
                            Id = "40",
                            Count = 35,
                            OrderId = "26",
                            Position = 1,
                            ProductId = "1"
                        },
                        new
                        {
                            Id = "41",
                            Count = 45,
                            OrderId = "27",
                            Position = 1,
                            ProductId = "1"
                        },
                        new
                        {
                            Id = "42",
                            Count = 2,
                            OrderId = "28",
                            Position = 1,
                            ProductId = "1"
                        },
                        new
                        {
                            Id = "43",
                            Count = 1,
                            OrderId = "29",
                            Position = 1,
                            ProductId = "1"
                        });
                });

            modelBuilder.Entity("OrderManagement.Backend.DataModels.Product", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ParentId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("ParentId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = "1",
                            Name = "Milch",
                            ParentId = "1",
                            Price = 1.25m
                        },
                        new
                        {
                            Id = "2",
                            Name = "Butter",
                            ParentId = "1",
                            Price = 2.3m
                        },
                        new
                        {
                            Id = "3",
                            Name = "Salat",
                            ParentId = "2",
                            Price = 3.6m
                        },
                        new
                        {
                            Id = "4",
                            Name = "Pfanne",
                            ParentId = "3",
                            Price = 10.95m
                        },
                        new
                        {
                            Id = "5",
                            Name = "Speck",
                            ParentId = "4",
                            Price = 2.65m
                        },
                        new
                        {
                            Id = "6",
                            Name = "Kaese",
                            ParentId = "1",
                            Price = 2.50m
                        },
                        new
                        {
                            Id = "7",
                            Name = "Landjaeger",
                            ParentId = "4",
                            Price = 1.20m
                        },
                        new
                        {
                            Id = "8",
                            Name = "Löffel",
                            ParentId = "3",
                            Price = 6.50m
                        },
                        new
                        {
                            Id = "9",
                            Name = "Kartoffel",
                            ParentId = "2",
                            Price = 7.65m
                        },
                        new
                        {
                            Id = "10",
                            Name = "Gurke",
                            ParentId = "2",
                            Price = 1.20m
                        },
                        new
                        {
                            Id = "11",
                            Name = "Mascarpone",
                            ParentId = "1",
                            Price = 1.30m
                        },
                        new
                        {
                            Id = "12",
                            Name = "Schinken",
                            ParentId = "4",
                            Price = 15.20m
                        },
                        new
                        {
                            Id = "13",
                            Name = "Salami",
                            ParentId = "4",
                            Price = 8.90m
                        },
                        new
                        {
                            Id = "14",
                            Name = "Zwiebel",
                            ParentId = "2",
                            Price = 0.20m
                        },
                        new
                        {
                            Id = "15",
                            Name = "Majonaise",
                            ParentId = "1",
                            Price = 3.35m
                        },
                        new
                        {
                            Id = "16",
                            Name = "Banane",
                            ParentId = "2",
                            Price = 1.60m
                        });
                });

            modelBuilder.Entity("OrderManagement.Backend.DataModels.ProductGroup", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ParentId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("ParentId");

                    b.ToTable("ProductGroups");

                    b.HasData(
                        new
                        {
                            Id = "1",
                            Name = "Products"
                        },
                        new
                        {
                            Id = "2",
                            Name = "Milch Produkte",
                            ParentId = "1"
                        },
                        new
                        {
                            Id = "3",
                            Name = "Fruechte / Gemuese",
                            ParentId = "1"
                        },
                        new
                        {
                            Id = "4",
                            Name = "Kuechenartikel",
                            ParentId = "1"
                        },
                        new
                        {
                            Id = "5",
                            Name = "Käse",
                            ParentId = "2"
                        },
                        new
                        {
                            Id = "6",
                            Name = "Appenzeller",
                            ParentId = "5"
                        },
                        new
                        {
                            Id = "7",
                            Name = "Schoggi-Milch",
                            ParentId = "2"
                        },
                        new
                        {
                            Id = "8",
                            Name = "Messer",
                            ParentId = "4"
                        },
                        new
                        {
                            Id = "9",
                            Name = "Erdbeeren",
                            ParentId = "5"
                        });
                });

            modelBuilder.Entity("OrderManagement.Backend.DataModels.Customer", b =>
                {
                    b.HasOne("OrderManagement.Backend.DataModels.Address", "Address")
                        .WithMany("Customers")
                        .HasForeignKey("AddressId");

                    b.Navigation("Address");
                });

            modelBuilder.Entity("OrderManagement.Backend.DataModels.Order", b =>
                {
                    b.HasOne("OrderManagement.Backend.DataModels.Customer", "Customer")
                        .WithMany("Orders")
                        .HasForeignKey("CustomerId");

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("OrderManagement.Backend.DataModels.OrderPosition", b =>
                {
                    b.HasOne("OrderManagement.Backend.DataModels.Order", "Order")
                        .WithMany("Positions")
                        .HasForeignKey("OrderId");

                    b.HasOne("OrderManagement.Backend.DataModels.Product", "Product")
                        .WithMany("OrderPositions")
                        .HasForeignKey("ProductId");

                    b.Navigation("Order");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("OrderManagement.Backend.DataModels.Product", b =>
                {
                    b.HasOne("OrderManagement.Backend.DataModels.ProductGroup", "Parent")
                        .WithMany("Products")
                        .HasForeignKey("ParentId");

                    b.Navigation("Parent");
                });

            modelBuilder.Entity("OrderManagement.Backend.DataModels.ProductGroup", b =>
                {
                    b.HasOne("OrderManagement.Backend.DataModels.ProductGroup", "Parent")
                        .WithMany("Children")
                        .HasForeignKey("ParentId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Parent");
                });

            modelBuilder.Entity("OrderManagement.Backend.DataModels.Address", b =>
                {
                    b.Navigation("Customers");
                });

            modelBuilder.Entity("OrderManagement.Backend.DataModels.Customer", b =>
                {
                    b.Navigation("Orders");
                });

            modelBuilder.Entity("OrderManagement.Backend.DataModels.Order", b =>
                {
                    b.Navigation("Positions");
                });

            modelBuilder.Entity("OrderManagement.Backend.DataModels.Product", b =>
                {
                    b.Navigation("OrderPositions");
                });

            modelBuilder.Entity("OrderManagement.Backend.DataModels.ProductGroup", b =>
                {
                    b.Navigation("Children");

                    b.Navigation("Products");
                });
#pragma warning restore 612, 618
        }
    }
}
